src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotNull
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\NotBlank
     * * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     * @Assert\Regex(pattern="/^\pL+$/u",
     *     match=true,
     *     message="Your name cannot contain a number")
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\Length(
     *      min = 2,
     *      max = 50,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     * @Assert\Regex(
     *     pattern="/^\pL+$/u",
     *     match=true,
     *     message="Your name cannot contain a number"
     * )
     */
    private $given_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\Regex(
     *     pattern="/^\pL+$/u",
     *     match=true,
     *     message="Your name cannot contain a number"
     * )
     */
    private $street_name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $street_number;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\Regex(
     *     pattern="/^\d+$/",
     *     match=true,
     *     message="Streetnumber cannot contain a Letter"
     * )
     */
    private $post_code;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\Regex(
     *     pattern="/^\d+$/",
     *     match=true,
     *     message="Phonenumber cannot contain a Letter"
     * )
     */
    private $phone_number;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string)$this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getGivenName(): ?string
    {
        return $this->given_name;
    }

    public function setGivenName(string $given_name): self
    {
        $this->given_name = $given_name;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->street_name;
    }

    public function setStreetName(string $street_name): self
    {
        $this->street_name = $street_name;

        return $this;
    }

    public function getStreetNumber(): ?string
    {
        return $this->street_number;
    }

    public function setStreetNumber(string $street_number): self
    {
        $this->street_number = $street_number;

        return $this;
    }

    public function getPostCode(): ?string
    {
        return $this->post_code;
    }

    public function setPostCode(string $post_code): self
    {
        $this->post_code = $post_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
}

src/Controller/DetailsController.php
<?php

namespace App\Controller;

use App\Form\DetailsFormType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class DetailsController extends AbstractController
{
    /**
     * @param Request $request
     * @param string $email
     * @param UserRepository $userRepository
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     */

    #[Route('/details/{email}', name: 'details')]
    public function index(Request $request, string $email, UserRepository $userRepository, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $error = "";

        if(!$this->getUser()->isVerified()){
            return $this->render('registration/verify_email.html.twig', [
                'error' => 'Please check your Emails and verify your Account first'
            ]);
        }

        if($this->getUser()->getEmail() === $email){
            return $this->redirectToRoute('mydata');
        }

        if ($selectedUser = $userRepository->findByEmailField($email)) {
            $entityManager = $this->getDoctrine()->getManager();
            $form = $this->createForm(DetailsFormType::class, $selectedUser);
            $form->handleRequest($request);
            if ($form->getClickedButton() && 'update' ===  $form->getClickedButton()->getName()) {
                $plainPassword = $form->get('plainPassword')->getData();
                $repeatPassword = $form->get('rPlainPassword')->getData();
                if($plainPassword && $repeatPassword){
                    if($plainPassword === $repeatPassword) {
                        $user = $form->getData();
                        $user->setPassword(
                            $passwordEncoder->encodePassword(
                                $user,
                                $form->get('plainPassword')->getData()
                            )
                        );
                    }
                }
                if($roles = $form->get('roles')->getData()){
                  $selectedUser->setRoles([$roles]);
                }

                $entityManager->flush();
                $error = "Update successfully";
            }
            if ($form->getClickedButton() && 'delete' ===  $form->getClickedButton()->getName()) {
                $entityManager->remove($selectedUser);
                $entityManager->flush();
                return $this->redirectToRoute('list_persons');
            }

            return $this->render('details/index.html.twig', [
                'details' => $form->createView(),
                'user' => $selectedUser,
                'error' => $error,
            ]);
        }

        return $this->redirectToRoute('list_persons');
    }
}

src/Controller/Web/DetailsController.php
<?php

namespace App\Controller\Web;

use App\Form\DetailsFormType;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class DetailsController extends AbstractController
{
    /**
     * @param Request $request
     * @param string $email
     * @param UserRepository $userRepository
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return Response
     * @throws \Doctrine\ORM\NonUniqueResultException
     */

    #[Route('/details/{email}', name: 'details')]
    public function index(Request $request, string $email, UserRepository $userRepository, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $error = "";

        if(!$this->getUser()->isVerified()){
            return $this->render('registration/verify_email.html.twig', [
                'error' => 'Please check your Emails and verify your Account first'
            ]);
        }

        if($this->getUser()->getEmail() === $email){
            return $this->redirectToRoute('mydata');
        }

        if ($selectedUser = $userRepository->findByEmailField($email)) {
            $entityManager = $this->getDoctrine()->getManager();
            $form = $this->createForm(DetailsFormType::class, $selectedUser);
            $form->handleRequest($request);
            if ($form->getClickedButton() && 'update' ===  $form->getClickedButton()->getName()) {
                $plainPassword = $form->get('plainPassword')->getData();
                $repeatPassword = $form->get('rPlainPassword')->getData();
                if($plainPassword && $repeatPassword){
                    if($plainPassword === $repeatPassword) {
                        $user = $form->getData();
                        $user->setPassword(
                            $passwordEncoder->encodePassword(
                                $user,
                                $form->get('plainPassword')->getData()
                            )
                        );
                    }
                }
                if($roles = $form->get('roles')->getData()){
                  $selectedUser->setRoles([$roles]);
                }

                $entityManager->flush();
                $error = "Update successfully";
            }
            if ($form->getClickedButton() && 'delete' ===  $form->getClickedButton()->getName()) {
                $entityManager->remove($selectedUser);
                $entityManager->flush();
                return $this->redirectToRoute('list_persons');
            }

            return $this->render('details/index.html.twig', [
                'details' => $form->createView(),
                'user' => $selectedUser,
                'error' => $error,
            ]);
        }

        return $this->redirectToRoute('list_persons');
    }
}

templates/details/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Details{% endblock %}
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('css/sidebars.css') }}"
        {% endblock %}

        {% block javascripts %}
            <script src="{{ asset('js/sidebars.js') }}"></script>
        {% endblock %}
{% block body %}
    <body>
    {{ include('sidenav.html.twig') }}
    <main>
        <div class="container">
            <br>
            <h1>{{ user.firstname }}  {{ user.givenname }} Status: {{ user.roles[0] }}</h1>
            <form method="post">
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_HR")%}
                            {{ form_label(details.email, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.email, {'attr': {'class': 'form-control'}}) }}
                        {% else %}
                            <a>{{ user.email }}</a>
                        {% endif %}
                    </div>
                </div>
                {% if is_granted("ROLE_ADMIN")%}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            {{ form_label(details.plainPassword, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.plainPassword, {'attr': {'class': 'form-control', 'placeholder': 'Repeat Password'}}) }}
                        </div>
                        <div class="form-group col-md-6">
                            {{ form_label(details.rPlainPassword, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.rPlainPassword, {'attr': {'class': 'form-control', 'placeholder': 'Repeat Password'}}) }}
                        </div>
                    </div>
                {% endif %}
                <div class="form-row">
                    <div class="form-group col-md-12">
                        {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_HR")%}
                            {{ form_label(details.firstName, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.firstName, {'attr': {'class': 'form-control'}}) }}
                        {% else %}
                            <a>{{ user.firstname }}</a>
                        {% endif %}
                    </div>
                    <div class="form-group col-md-12">
                        {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_HR")%}
                            {{ form_label(details.givenName, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.givenName, {'attr': {'class': 'form-control'}}) }}
                        {% else %}
                            <a>{{ user.givenname }} </a>
                        {% endif %}
                    </div>
                </div>
                {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_HR")%}
                    <div class="form-row">
                        <div class="form-group col-md-9">
                            {{ form_label(details.streetName, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.streetName, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group col-md-3">
                            {{ form_label(details.streetNumber, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.streetNumber, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-8">
                            {{ form_label(details.postCode, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.postCode, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group col-md-4">
                            {{ form_label(details.city, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.city, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    </div>
                {% else %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <a>{{ user.streetname }} {{ user.streetnumber }}</a>
                        </div>
                        <div class="form-group col-md-12">
                            <a>{{ user.postcode }} {{ user.city }}</a>
                        </div>
                    </div>
                {% endif %}
                <div class="form-row">
                    <div class="form-group col-md-9">
                        {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_HR")%}
                            {{ form_label(details.phoneNumber, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.phoneNumber, {'attr': {'class': 'form-control'}}) }}
                        {% else %}
                            <a>{{ user.phonenumber }}</a>
                        {% endif %}
                    </div>
                    {% if is_granted("ROLE_ADMIN")%}
                        <div class='form-group col-md-3'>
                            {{ form_label(details.roles, null, {'label_attr': {'class': 'sr-only'}}) }}
                            {{ form_widget(details.roles, {'attr': {'class': 'form-control'}}) }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-row">
                    {% if is_granted("ROLE_ADMIN") or is_granted("ROLE_HR")%}
                        <div class="form-group col-md-6">
                            {{ form_label(details.update) }}
                            {{ form_widget(details.update, {'attr': {'class': 'w-100 btn btn-primary btn-lg'}}) }}
                        </div>
                    {% endif %}
                    {% if is_granted("ROLE_ADMIN")%}
                        <div class="form-group col-md-6">
                            {{ form_label(details.delete) }}
                            {{ form_widget(details.delete, {'attr': {'class': 'w-100 btn btn-primary btn-lg'}}) }}
                        </div>
                    {% endif %}
                </div>
                {% if error %}
                    <div class="alert alert-success">{{ error }}</div>
                {% endif %}
            </form>
        </div>
    </main>
    </body>
{% endblock %}